version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - mkdir /downloads/sonarqube -p
    - cd /downloads/sonarqube
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
    - unzip sonar-scanner-cli-4.2.0.1873-linux.zip
    - mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
    - echo  "la ip de sonar es $IP_SONAR"
    - echo -e "sonar.host.url=http://$IP_SONAR:9000/ \n  sonar.sourceEncoding=UTF-8 \n sonar.qualitygate.wait=true " >> /opt/sonar-scanner/conf/sonar-scanner.properties
    - echo -e "#/bin/bash \n export PATH='$PATH:/opt/sonar-scanner/bin'" >> /etc/profile.d/sonar-scanner.sh
    - source /etc/profile.d/sonar-scanner.sh
  build:
    commands:
    - cd ../..
    - cd /codebuild/output/src*/src
    - mvn clean verify sonar:sonar -Dsonar.projectKey=$PROJECT_KEY_SONAR -Dsonar.projectName='$PROJECT_KEY_SONAR' -Dsonar.host.url=http://"$IP_SONAR":9000 -Dsonar.token=$TOKEN_SONAR